# permissions for end users to edit canaryreleases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: canaryrelease-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: canary-operator
    app.kubernetes.io/part-of: canary-operator
    app.kubernetes.io/managed-by: kustomize
  name: canaryrelease-editor-role
rules:
- apiGroups:
  - release.example.com
  resources:
  - canaryreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - release.example.com
  resources:
  - canaryreleases/status
  verbs:
  - get
